"""Processing subpackage — normalization, sections, chunking, and embeddings."""

from pipeline.processing.normalization import (
    BULLET_START_PATTERN,
    HEADER_PREFIX_PATTERN,
    NUMBERED_HEADER_PATTERN,
    PAGE_MARKER_PATTERN,
    SEPARATOR_LINE_PATTERN,
    SPEAKER_LABEL_PATTERN,
    TABLE_SPLIT_PATTERN,
    approximate_word_count,
    is_probable_header_line,
    make_processing_note,
    normalize_bullets_and_lists,
    normalize_document_text,
    normalize_line_breaks,
    normalize_table_like_text,
    normalize_whitespace,
    preserve_meaningful_headers,
    safe_text_cleanup,
    strip_noise_blocks,
)
from pipeline.processing.sections import (
    classify_section_kind,
    detect_document_sections,
    extract_reference_label,
    infer_section_level,
    process_selected_document,
    selected_document_from_candidate,
    selected_document_from_retrieval_result,
)
from pipeline.processing.chunking import (
    assign_chunk_ids,
    build_chunks_from_sections,
    build_document_chunks,
    build_fallback_chunks,
    slice_text_with_overlap,
    split_section_into_blocks,
    summarize_chunk_context,
)
from pipeline.processing.embeddings import (
    BaseEmbeddingClient,
    VoyageAIEmbeddingClient,
    batch_embed_texts,
    build_chunk_embedding_lookup,
    build_chunk_embedding_records,
    build_document_graph,
    build_embedding_client,
    cosine_similarity,
    expand_chunk_context,
    get_neighbor_chunks,
    l2_normalize,
    make_text_excerpt,
    retrieve_relevant_chunks,
    score_chunk_with_graph_context,
    tokenize_for_embedding,
)

__all__ = [
    # normalization
    "BULLET_START_PATTERN",
    "HEADER_PREFIX_PATTERN",
    "NUMBERED_HEADER_PATTERN",
    "PAGE_MARKER_PATTERN",
    "SEPARATOR_LINE_PATTERN",
    "SPEAKER_LABEL_PATTERN",
    "TABLE_SPLIT_PATTERN",
    "approximate_word_count",
    "is_probable_header_line",
    "make_processing_note",
    "normalize_bullets_and_lists",
    "normalize_document_text",
    "normalize_line_breaks",
    "normalize_table_like_text",
    "normalize_whitespace",
    "preserve_meaningful_headers",
    "safe_text_cleanup",
    "strip_noise_blocks",
    # sections
    "classify_section_kind",
    "detect_document_sections",
    "extract_reference_label",
    "infer_section_level",
    "process_selected_document",
    "selected_document_from_candidate",
    "selected_document_from_retrieval_result",
    # chunking
    "assign_chunk_ids",
    "build_chunks_from_sections",
    "build_document_chunks",
    "build_fallback_chunks",
    "slice_text_with_overlap",
    "split_section_into_blocks",
    "summarize_chunk_context",
    # embeddings
    "BaseEmbeddingClient",
    "VoyageAIEmbeddingClient",
    "batch_embed_texts",
    "build_chunk_embedding_lookup",
    "build_chunk_embedding_records",
    "build_document_graph",
    "build_embedding_client",
    "cosine_similarity",
    "expand_chunk_context",
    "get_neighbor_chunks",
    "l2_normalize",
    "make_text_excerpt",
    "retrieve_relevant_chunks",
    "score_chunk_with_graph_context",
    "tokenize_for_embedding",
]
