"""Arbiter subpackage: cross-document arbitration, normalization, and confidence."""

from pipeline.arbiter.models import (
    EXPECTED_DOCUMENT_TYPES,
    STRUCTURED_DOCUMENT_TYPES,
    SOFT_DOCUMENT_TYPES,
    THEME_LABELS,
    THEME_DOCUMENT_RELEVANCE,
    USABLE_WORKER_STATUSES,
    ArbiterIssue,
    ArbiterWarning,
    ArbiterEvidenceReference,
    NormalizedSignalDirection,
    ArbiterSignalCategory,
    stable_unique,
    document_type_label,
    make_arbiter_issue,
    make_arbiter_warning,
    worker_status_rank,
    worker_output_quality_key,
    select_best_worker_output_per_type,
    flatten_worker_evidence_references,
    deduplicate_arbiter_evidence,
    deduplicate_evidence_snippets,
    convert_worker_pipeline_issue_to_arbiter_issue,
    extract_worker_signal_profile,
)
from pipeline.arbiter.normalization import (
    clamp_value,
    safe_mean,
    normalize_signal_direction,
    normalize_worker_output_for_arbitration,
    build_standardized_analysis_score as arbiter_build_standardized_analysis_score,
)
from pipeline.arbiter.cross_document import (
    build_cross_document_themes,
    summarize_theme_support,
    build_theme_judgment,
    detect_cross_document_alignment,
    signals_form_conflict,
    detect_cross_document_conflicts,
    compare_worker_outputs,
    make_finding_from_judgment,
    make_signal_group_from_judgment,
    group_positive_signals,
    group_negative_signals,
    build_sparse_worker_uncertainty_finding,
    group_uncertainties,
    detect_story_vs_substance_mismatch,
    group_fogging_concerns,
    aggregate_arbiter_sentiment,
    aggregate_arbiter_tone,
    BaseArbiter,
    CrossDocumentArbiter,
    ARBITER_REGISTRY,
)
from pipeline.arbiter.confidence import (
    make_confidence_adjustment,
    adjust_confidence_for_evidence_density,
    adjust_confidence_for_conflict,
    adjust_confidence_for_missing_coverage,
    adjust_confidence_for_structured_support,
    assess_cross_document_confidence,
    build_missing_coverage_notes,
    build_arbiter_warnings,
)

__all__ = [
    # models
    "EXPECTED_DOCUMENT_TYPES",
    "STRUCTURED_DOCUMENT_TYPES",
    "SOFT_DOCUMENT_TYPES",
    "THEME_LABELS",
    "THEME_DOCUMENT_RELEVANCE",
    "USABLE_WORKER_STATUSES",
    "ArbiterIssue",
    "ArbiterWarning",
    "ArbiterEvidenceReference",
    "NormalizedSignalDirection",
    "ArbiterSignalCategory",
    "stable_unique",
    "document_type_label",
    "make_arbiter_issue",
    "make_arbiter_warning",
    "worker_status_rank",
    "worker_output_quality_key",
    "select_best_worker_output_per_type",
    "flatten_worker_evidence_references",
    "deduplicate_arbiter_evidence",
    "deduplicate_evidence_snippets",
    "convert_worker_pipeline_issue_to_arbiter_issue",
    "extract_worker_signal_profile",
    # normalization
    "clamp_value",
    "safe_mean",
    "normalize_signal_direction",
    "normalize_worker_output_for_arbitration",
    "arbiter_build_standardized_analysis_score",
    # cross_document
    "build_cross_document_themes",
    "summarize_theme_support",
    "build_theme_judgment",
    "detect_cross_document_alignment",
    "signals_form_conflict",
    "detect_cross_document_conflicts",
    "compare_worker_outputs",
    "make_finding_from_judgment",
    "make_signal_group_from_judgment",
    "group_positive_signals",
    "group_negative_signals",
    "build_sparse_worker_uncertainty_finding",
    "group_uncertainties",
    "detect_story_vs_substance_mismatch",
    "group_fogging_concerns",
    "aggregate_arbiter_sentiment",
    "aggregate_arbiter_tone",
    "BaseArbiter",
    "CrossDocumentArbiter",
    "ARBITER_REGISTRY",
    # confidence
    "make_confidence_adjustment",
    "adjust_confidence_for_evidence_density",
    "adjust_confidence_for_conflict",
    "adjust_confidence_for_missing_coverage",
    "adjust_confidence_for_structured_support",
    "assess_cross_document_confidence",
    "build_missing_coverage_notes",
    "build_arbiter_warnings",
]
